{
    "input": {
      "dvid": {
        "server": "127.0.0.1:8000",
        "uuid": "UUID1",
        "segmentation-name": "labels",
        "supervoxels": true
      },
      "geometry": {
        "bounding-box": [[0,0,0], [256,256,256]],
        "message-block-shape": [6400,64,64],
        "available-scales": [0,1,2,3]
      },
      "rescale-level": 1
    },
    "output": {
      "dvid": {
        "server": "127.0.0.1:8000",
        "uuid": "UUID1",
        "segmentation-name": "labels",
        "meshes-destination": "labels_sv_meshes"
      },
      "geometry": {} # Not used
    },
    "mesh-config": {
        task-block-shape: [64, 64, 64],
        task-block-halo: 2,

        pre-stitch-smoothing-iterations: 3,
        pre-stitch-decimation: 0.1,

        stitch-method: simple-concatenate,

        post-stitch-smoothing-iterations: 0, # None
        post-stitch-decimation: 1.0, # None
        
        "storage": {
          #format: drc,
          format: obj,
          naming-scheme: "tarsupervoxels",
          "grouping-scheme": "labelmap",
          "labelmap": {
            "file": ../mod-10-labelmap.csv, # Relative to temp_data/config.json
            "file-type": label-to-body
          },
          "subset-bodies": ../subset-bodies-odd-only.csv
        }
    },
    "options": {
        "minimum-segment-size": 10000,
        "minimum-agglomerated-size": 100000,

        "resource-server": "driver",
        "resource-port": 4000,

        "resource-server-config": {
            "read_reqs": 128,
            "read_data": 4000000000,
            "write_reqs": 128,
            "write_data": 4000000000
        },
                
        "log-collector-port": 3000,
        "log-collector-directory": "./logs"
    }
}
