{
    "dvid-info": {
      "dvid": {
        "server": "127.0.0.1:8000",
        "uuid": "UUID1",
        "segmentation-name": "labels",
        "meshes-destination": "labels_grouped_stitched_meshes"
      },
      "geometry": {
        "bounding-box": [[0,0,0], [256,256,256]],
        "message-block-shape": [6400,64,64]
      }
    },
    "mesh-config": {
        #"task-block-shape": [64, 64, 64],
        "task-block-halo": 2,
        "simplify-ratios": [0.1],
        "step-size": 1,
        "storage": {
          format: drc,
          #format: obj,
          naming-scheme: "neu3-level-0",
          "grouping-scheme": "labelmap",
          "labelmap": {
            "file": ../mod-10-labelmap.csv, # Relative to temp_data/config.json
            "file-type": label-to-body
          },
        }
    },
    "options": {
        "minimum-segment-size": 10000,
        "minimum-agglomerated-size": 10000,

        "resource-server": "driver",
        "resource-port": 4000,

        "resource-server-config": {
            "read_reqs": 128,
            "read_data": 4000000000,
            "write_reqs": 128,
            "write_data": 4000000000
        },
                
        "log-collector-port": 3000,
        "log-collector-directory": "./logs"
    }
}
