input:
  dvid:
    server: "127.0.0.1:8000"
    uuid: "UUID1"
    segmentation-name: "labels"
    supervoxels: true
    
  geometry:
    bounding-box: [[100, 150, 200], [356, 406, 456]]

options:
  input-table: ../points.csv # Relative to temp_data/

  resource-server: driver
  resource-port: 4000
  resource-server-config:
    read_reqs: 128
    read_data: 4000000000
    write_reqs: 128
    write_data: 4000000000

  log-collector-directory: /tmp/test_samplepoints_logs
  log-collector-port: 3000

  debug: false
