{
    "dvid-info": {
        "dvid-server": "127.0.0.1:8000",
        "uuid": "UUID1",
        "label-name": "labels",
        "roi": "temproi",
        "point-lists": ["syn"],
        "stats-location": "off1.seg"
    },
    "dvid-info-comp": {
        "dvid-server": "127.0.0.1:8000",
        "uuid": "UUID2",
        "label-name": "labels"
    },
    "options": {
        "body-threshold": 1000,
        "point-threshold": 0,
        "boundary-size": 2,
        "user-name": "plazas",
        "chunk-size": 64,
        "spark-config": {},
        "worker-initialization": {
            "script-path": false
        },
        "resource-server": "driver",
        "resource-port": 4000,

        "resource-server-config": {
            "read_reqs": 128,
            "read_data": 4000000000,
            "write_reqs": 128,
            "write_data": 4000000000
        }
    },
    "debug": true
}
