# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: labelindex.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='labelindex.proto',
  package='proto',
  syntax='proto3',
  serialized_pb=_b('\n\x10labelindex.proto\x12\x05proto\"8\n\x07MergeOp\x12\r\n\x05mutid\x18\x01 \x01(\x04\x12\x0e\n\x06target\x18\x02 \x01(\x04\x12\x0e\n\x06merged\x18\x03 \x03(\x04\"X\n\x07SplitOp\x12\r\n\x05mutid\x18\x01 \x01(\x04\x12\x0e\n\x06target\x18\x02 \x01(\x04\x12\x10\n\x08newlabel\x18\x03 \x01(\x04\x12\x0e\n\x06\x63oarse\x18\x04 \x01(\x08\x12\x0c\n\x04rles\x18\x05 \x01(\x0c\"+\n\x0bOpCompleted\x12\r\n\x05mutid\x18\x01 \x01(\x04\x12\r\n\x05stage\x18\x02 \x01(\t\"0\n\nAffinities\x12\x0e\n\x06labels\x18\x01 \x03(\x04\x12\x12\n\naffinities\x18\x02 \x03(\x02\"\x80\x01\n\rAffinityTable\x12.\n\x05table\x18\x01 \x03(\x0b\x32\x1f.proto.AffinityTable.TableEntry\x1a?\n\nTableEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.proto.Affinities:\x02\x38\x01\"d\n\x07SVCount\x12*\n\x06\x63ounts\x18\x01 \x03(\x0b\x32\x1a.proto.SVCount.CountsEntry\x1a-\n\x0b\x43ountsEntry\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\r:\x02\x38\x01\"\xc2\x01\n\rLabelSetIndex\x12\x30\n\x06\x62locks\x18\x01 \x03(\x0b\x32 .proto.LabelSetIndex.BlocksEntry\x12\x12\n\nlast_mutid\x18\x03 \x01(\x04\x12\x15\n\rlast_mod_time\x18\x04 \x01(\t\x12\x15\n\rlast_mod_user\x18\x05 \x01(\t\x1a=\n\x0b\x42locksEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1d\n\x05value\x18\x02 \x01(\x0b\x32\x0e.proto.SVCount:\x02\x38\x01\x62\x06proto3')
)




_MERGEOP = _descriptor.Descriptor(
  name='MergeOp',
  full_name='proto.MergeOp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mutid', full_name='proto.MergeOp.mutid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target', full_name='proto.MergeOp.target', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='merged', full_name='proto.MergeOp.merged', index=2,
      number=3, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=83,
)


_SPLITOP = _descriptor.Descriptor(
  name='SplitOp',
  full_name='proto.SplitOp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mutid', full_name='proto.SplitOp.mutid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target', full_name='proto.SplitOp.target', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='newlabel', full_name='proto.SplitOp.newlabel', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='coarse', full_name='proto.SplitOp.coarse', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rles', full_name='proto.SplitOp.rles', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=173,
)


_OPCOMPLETED = _descriptor.Descriptor(
  name='OpCompleted',
  full_name='proto.OpCompleted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mutid', full_name='proto.OpCompleted.mutid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stage', full_name='proto.OpCompleted.stage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=218,
)


_AFFINITIES = _descriptor.Descriptor(
  name='Affinities',
  full_name='proto.Affinities',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='labels', full_name='proto.Affinities.labels', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='affinities', full_name='proto.Affinities.affinities', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=220,
  serialized_end=268,
)


_AFFINITYTABLE_TABLEENTRY = _descriptor.Descriptor(
  name='TableEntry',
  full_name='proto.AffinityTable.TableEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proto.AffinityTable.TableEntry.key', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.AffinityTable.TableEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=399,
)

_AFFINITYTABLE = _descriptor.Descriptor(
  name='AffinityTable',
  full_name='proto.AffinityTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table', full_name='proto.AffinityTable.table', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_AFFINITYTABLE_TABLEENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=399,
)


_SVCOUNT_COUNTSENTRY = _descriptor.Descriptor(
  name='CountsEntry',
  full_name='proto.SVCount.CountsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proto.SVCount.CountsEntry.key', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.SVCount.CountsEntry.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=456,
  serialized_end=501,
)

_SVCOUNT = _descriptor.Descriptor(
  name='SVCount',
  full_name='proto.SVCount',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='counts', full_name='proto.SVCount.counts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SVCOUNT_COUNTSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=401,
  serialized_end=501,
)


_LABELSETINDEX_BLOCKSENTRY = _descriptor.Descriptor(
  name='BlocksEntry',
  full_name='proto.LabelSetIndex.BlocksEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='proto.LabelSetIndex.BlocksEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='proto.LabelSetIndex.BlocksEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=637,
  serialized_end=698,
)

_LABELSETINDEX = _descriptor.Descriptor(
  name='LabelSetIndex',
  full_name='proto.LabelSetIndex',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='blocks', full_name='proto.LabelSetIndex.blocks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_mutid', full_name='proto.LabelSetIndex.last_mutid', index=1,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_mod_time', full_name='proto.LabelSetIndex.last_mod_time', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_mod_user', full_name='proto.LabelSetIndex.last_mod_user', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_LABELSETINDEX_BLOCKSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=504,
  serialized_end=698,
)

_AFFINITYTABLE_TABLEENTRY.fields_by_name['value'].message_type = _AFFINITIES
_AFFINITYTABLE_TABLEENTRY.containing_type = _AFFINITYTABLE
_AFFINITYTABLE.fields_by_name['table'].message_type = _AFFINITYTABLE_TABLEENTRY
_SVCOUNT_COUNTSENTRY.containing_type = _SVCOUNT
_SVCOUNT.fields_by_name['counts'].message_type = _SVCOUNT_COUNTSENTRY
_LABELSETINDEX_BLOCKSENTRY.fields_by_name['value'].message_type = _SVCOUNT
_LABELSETINDEX_BLOCKSENTRY.containing_type = _LABELSETINDEX
_LABELSETINDEX.fields_by_name['blocks'].message_type = _LABELSETINDEX_BLOCKSENTRY
DESCRIPTOR.message_types_by_name['MergeOp'] = _MERGEOP
DESCRIPTOR.message_types_by_name['SplitOp'] = _SPLITOP
DESCRIPTOR.message_types_by_name['OpCompleted'] = _OPCOMPLETED
DESCRIPTOR.message_types_by_name['Affinities'] = _AFFINITIES
DESCRIPTOR.message_types_by_name['AffinityTable'] = _AFFINITYTABLE
DESCRIPTOR.message_types_by_name['SVCount'] = _SVCOUNT
DESCRIPTOR.message_types_by_name['LabelSetIndex'] = _LABELSETINDEX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MergeOp = _reflection.GeneratedProtocolMessageType('MergeOp', (_message.Message,), dict(
  DESCRIPTOR = _MERGEOP,
  __module__ = 'labelindex_pb2'
  # @@protoc_insertion_point(class_scope:proto.MergeOp)
  ))
_sym_db.RegisterMessage(MergeOp)

SplitOp = _reflection.GeneratedProtocolMessageType('SplitOp', (_message.Message,), dict(
  DESCRIPTOR = _SPLITOP,
  __module__ = 'labelindex_pb2'
  # @@protoc_insertion_point(class_scope:proto.SplitOp)
  ))
_sym_db.RegisterMessage(SplitOp)

OpCompleted = _reflection.GeneratedProtocolMessageType('OpCompleted', (_message.Message,), dict(
  DESCRIPTOR = _OPCOMPLETED,
  __module__ = 'labelindex_pb2'
  # @@protoc_insertion_point(class_scope:proto.OpCompleted)
  ))
_sym_db.RegisterMessage(OpCompleted)

Affinities = _reflection.GeneratedProtocolMessageType('Affinities', (_message.Message,), dict(
  DESCRIPTOR = _AFFINITIES,
  __module__ = 'labelindex_pb2'
  # @@protoc_insertion_point(class_scope:proto.Affinities)
  ))
_sym_db.RegisterMessage(Affinities)

AffinityTable = _reflection.GeneratedProtocolMessageType('AffinityTable', (_message.Message,), dict(

  TableEntry = _reflection.GeneratedProtocolMessageType('TableEntry', (_message.Message,), dict(
    DESCRIPTOR = _AFFINITYTABLE_TABLEENTRY,
    __module__ = 'labelindex_pb2'
    # @@protoc_insertion_point(class_scope:proto.AffinityTable.TableEntry)
    ))
  ,
  DESCRIPTOR = _AFFINITYTABLE,
  __module__ = 'labelindex_pb2'
  # @@protoc_insertion_point(class_scope:proto.AffinityTable)
  ))
_sym_db.RegisterMessage(AffinityTable)
_sym_db.RegisterMessage(AffinityTable.TableEntry)

SVCount = _reflection.GeneratedProtocolMessageType('SVCount', (_message.Message,), dict(

  CountsEntry = _reflection.GeneratedProtocolMessageType('CountsEntry', (_message.Message,), dict(
    DESCRIPTOR = _SVCOUNT_COUNTSENTRY,
    __module__ = 'labelindex_pb2'
    # @@protoc_insertion_point(class_scope:proto.SVCount.CountsEntry)
    ))
  ,
  DESCRIPTOR = _SVCOUNT,
  __module__ = 'labelindex_pb2'
  # @@protoc_insertion_point(class_scope:proto.SVCount)
  ))
_sym_db.RegisterMessage(SVCount)
_sym_db.RegisterMessage(SVCount.CountsEntry)

LabelSetIndex = _reflection.GeneratedProtocolMessageType('LabelSetIndex', (_message.Message,), dict(

  BlocksEntry = _reflection.GeneratedProtocolMessageType('BlocksEntry', (_message.Message,), dict(
    DESCRIPTOR = _LABELSETINDEX_BLOCKSENTRY,
    __module__ = 'labelindex_pb2'
    # @@protoc_insertion_point(class_scope:proto.LabelSetIndex.BlocksEntry)
    ))
  ,
  DESCRIPTOR = _LABELSETINDEX,
  __module__ = 'labelindex_pb2'
  # @@protoc_insertion_point(class_scope:proto.LabelSetIndex)
  ))
_sym_db.RegisterMessage(LabelSetIndex)
_sym_db.RegisterMessage(LabelSetIndex.BlocksEntry)


_AFFINITYTABLE_TABLEENTRY.has_options = True
_AFFINITYTABLE_TABLEENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_SVCOUNT_COUNTSENTRY.has_options = True
_SVCOUNT_COUNTSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_LABELSETINDEX_BLOCKSENTRY.has_options = True
_LABELSETINDEX_BLOCKSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
