# This test is designed to be run AFTER test_copyseg.
# Therefore, we refer to an outputs from that test as our inputs.
dvid:
  "server": "127.0.0.1:8000"
  "uuid": "UUID2"
  "segmentation-name": labels-copy-translated

block-stats-file: ../../test_copyseg/temp_data/block-statistics.csv
agglomeration-mapping:
  file: ../../test_copyseg/LABEL-TO-BODY-mod-100-labelmap.csv
  file-type: label-to-body

options:
  operation: both
  mutation-id: 1
