package:
  name: dvidsparkservices 

  # If we're using a non-tagged revision, append '.postN' to the version
  {% if GIT_DESCRIBE_NUMBER|int != 0 %}
  version: {{GIT_DESCRIBE_TAG}}.post{{GIT_DESCRIBE_NUMBER}}
  {% else %}
  version: {{GIT_DESCRIBE_TAG}}
  {% endif %}

source:
  path: ../

build:
  number: 0
  string: py{{CONDA_PY}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}

  noarch: python  
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - launchworkflow = DVIDSparkServices.workflow.launchworkflow:main
    - sparklaunch_janelia_lsf = DVIDSparkServices.spark_launch_scripts.janelia_lsf.sparklaunch_janelia_lsf:main
    - sparklaunch_janelia_lsf_int = DVIDSparkServices.spark_launch_scripts.janelia_lsf.sparklaunch_janelia_lsf_int:main

requirements:
  build:
    - python >=3.6
    - python {{PY_VER}}*
    - setuptools
  run:
    - python >=3.6
    - python {{PY_VER}}*
    - jsonschema
    - pyspark
    - numpy
    - numba
    - neuroproof
    - neutube-python >=0.1.post8
    - libdvid-cpp >=0.2
    - neuclease
    - requests
    - scikit-image
    - pillow
    - scipy
    - python-lz4
    - python-snappy
    #- ilastik-versions-no-solvers  1.2  np111py27_14   # [osx]
    #- ilastik-versions-no-solvers  1.2  np111py27_12   # [linux]
    #- ilastik-meta
    - quilted >=0.0.post13
    - logcollector >=0.1.post13
    - dvid-resource-manager
    - psutil
    - pandas
    - munkres
    - ruamel.yaml >=0.15.34 # Required for YAML 1.2 support (pyyaml supports 1.1)
    - z5py
    - google-cloud-storage
    - tblib
    - dvidutils >=0.0.post44
    - pyspark-flame
    - tqdm # For progress bar reporting
    - protobuf
    
    # Needed for brainmaps support:
    - httplib2
    - oauth2client

test:
  requires:
    - nose
    - numpy-allocation-tracking

  imports:
    - DVIDSparkServices
    #- ilastik

about:
  home: http://github.com/janelia-flyem/DVIDSparkServices
  license: BSD (3-clause)
  license_file: LICENSE.txt
  summary: Python framework for EM Spark-based services 
