package:
  name: dvidsparkservices 

  # If we're using a non-tagged revision, append '.postN' to the version
  {% if GIT_DESCRIBE_NUMBER|int != 0 %}
  version: {{GIT_DESCRIBE_TAG}}.post{{GIT_DESCRIBE_NUMBER}}
  {% else %}
  version: {{GIT_DESCRIBE_TAG}}
  {% endif %}

source:
  git_url: ../
  git_tag: HEAD

build:
  number: 0
  string: py{{CONDA_PY}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}
  
  entry_points:
    - launchworkflow = DVIDSparkServices.workflow.launchworkflow:main

requirements:
  build:
    - python 2.7*
    - setuptools
  run:
    - python 2.7*  
    - jsonschema
    - numpy
    - numba
    - neuroproof
    - neutube-python >=0.1.post8
    - libdvid-cpp >=0.2
    - requests
    - scikit-image
    - pillow
    - scipy
    - python-lz4
    - ilastik-versions-no-solvers  1.2  np111py27_14   # [osx]
    - ilastik-versions-no-solvers  1.2  np111py27_12   # [linux]
    - ilastik-meta
    - quilted >=0.0.post13
    - logcollector >=0.1.post13
    - dvid-resource-manager
    - psutil
    - pandas

test:
  requires:
    - nose
    - numpy-allocation-tracking

  imports:
    - DVIDSparkServices
    - ilastik

about:
  home: http://github.com/janelia-flyem/DVIDSparkServices
  license: BSD (3-clause)
  license_file: LICENSE.txt
  summary: Python framework for EM Spark-based services 
