{
    "dvid-info": {
      "dvid": {
        "server": "127.0.0.1:8000",
        "uuid": "UUID1",
        "segmentation-name": "labels",
        "meshes-destination": "labels_grouped_meshes"
      },
      "geometry": {
        "bounding-box": [[0,0,0], [256,256,256]],
        "message-block-shape": [6400,64,64]
      }
    },
    "skeleton-config": {
        "downsampleInterval": [0, 0, 0],
        "minimalLength": 3,
        "keepingSingleObject": true,
        "rebase": true,
        "fillingHole": true,
        "maximalDistance": 64
    },
    "mesh-config": {
        "simplify-ratio": 0.5,
        "step-size": 1,
        "storage": {
          "grouping-scheme": "labelmap",
          "labelmap": {
            "file": ../mod-10-labelmap.csv, # Relative to temp_data/config.json
            "file-type": label-to-body
          },
          "format": "obj"
        }
    },
    "options": {
        "output-types": ["mesh"],
        "downsample-factor": 2,
        "minimum-segment-size": 10000,
        "max-analysis-volume": 1e9,

        "resource-server": "driver",
        "resource-port": 4000,

        "resource-server-config": {
            "read_reqs": 128,
            "read_data": 4000000000,
            "write_reqs": 128,
            "write_data": 4000000000
        },
        
        "downsample-timeout": 10.0,
        "analysis-timeout": 10.0,
        
        "log-collector-port": 3000,
        "log-collector-directory": ""
    }
}
