# This looks like JSON, but it's technically YAML.
# Therefore, it is allowed to contain comments, like this one.
# It can't contain tab charaecters (\t), though
{
    "input": {
        "service-type": "dvid",
        "server": "127.0.0.1:8000",
        "uuid": "UUID1",
        "segmentation-name": "labels",
        "bounding-box": [[100, 150, 200], [356, 406, 456]],

        # Mapping adds 100 to every input pixel
        "apply-labelmap": {
          "file": "../input_mapping_plus100.csv",
          "file-type": "label-to-body"
        },

        "message-block-shape": [6400, 64, 64],
        "block-width": 64
    },

    "output": {
        "service-type": "dvid",
        "server": "127.0.0.1:8000",
        "uuid": "UUID2",
        "segmentation-name": "labels-copy",
        "bounding-box": [[0, 0, 0], [256, 256, 256]],

        # Mapping adds 200 to every (remapped input pixel)
        "apply-labelmap": {
          "file":  "../output_mapping_plus200.csv",
          "file-type": "label-to-body"
        },

        "message-block-shape": [6400, 64, 64],
        "block-width": 64
    },

    "options": {
        "pyramid-depth": 2,

        "body-sizes": {
            "output-path": "./body-sizes.h5",
            "minimum-size": 10
        },
        
        "resource-server": "",
        "resource-port": 0,

        "resource-server-config": {
            "read_reqs": 128,
            "read_data": 4000000000,
            "write_reqs": 128,
            "write_data": 4000000000
        },

        "log-collector-directory": "/tmp/test_copyseg_logs",
        "log-collector-port": 3000,

        "debug": false
    }
}
