input:
  n5:
    path: ../../resources/volume-256.n5 # Relative to ./temp_data
    dataset-name: s0
  geometry:
    bounding-box: [[0,0,0], [256,200,100]]
  transpose-axes: ['1-y', 'x', 'z'] # XY_CLOCKWISE_90


output:
  dvid:
    server: 127.0.0.1:8000
    uuid: 'UUID1'
    grayscale-name: 'grayscale-from-n5'
    compression: raw

options:
  max-pyramid-scale: 3
  pyramid-source: compute

  slab-depth: 64
  slab-axis: z

  contrast-adjustment: hotknife-destripe
  hotknife-seams: [-1,50,100,150,200] # Note: These are X-coordinates.
                                      #       The X-dimension is 200px wide AFTER transpose-axes setting is applied.
  

  resource-server: 'driver'
  resource-port: 4000
  resource-server-config: {}

  log-collector-port: 3000
  log-collector-directory: './logs'

  spark-config:
    spark.task.cpus: 1
    spark.task.maxFailures: 1
