input:
  dvid:
    server: '127.0.0.1:8000'
    uuid: 'UUID1'
    grayscale-name: 'grayscale'
  geometry:
    bounding-box: [[0,0,0], [256,256,256]]

output:
  slice-files:
    slice-path-format: './slices/z{:05}.png'

options:
  slices-per-slab: -1

  resource-server: 'driver'
  resource-port: 5000
  resource-server-config: {}

  log-collector-port: 3000
  log-collector-directory: '/tmp/'

  spark-config:
    spark.task.cpus: 1
    spark.task.maxFailures: 1
